### ISSUE TITLE
Flask API creation

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/Learn#185]
Learn the Flask framework

1. Study the methods. Eg: POST, GET
2. API study
3. 
Create 4 apis,
Addition
Subtraction
Multiply
Division
The input to these api should be 2 numbers and the response should contain the result. Also add validation also [eg. When only one number is sent as input param or for division when the denominator is zero it should respond as error stating Invalid input ]

Sample Application in Flask:
https://github.com/Team-Tomato/QuestionPaper_Backend

**Comment by PrajitRahul** [comment]
The task assigned to me is to use python flask, create a simple API and send it as PR.

**Comment by Madhumidhra** [comment]
Assign me

**Comment by AkbarHabeeb** [comment]
Done by @Madhumidhra
