### ISSUE TITLE
React basic track

### ISSUE THREAD

**Issue by AkbarHabeeb** [Team-Tomato/Learn#192]
1. Learn basic HTML, CSS
2. Learn JS syntax
3. Using Js, fetch the data from API and display as a table
4. Using react, do the task 3

**Comment by sudharsansrini** [comment]
Hiii anna.. Sudharsan😅

**Comment by BARANI2001** [comment]
Assign me this task Anna

**Comment by BARANI2001** [comment]
![Output_1](https://user-images.githubusercontent.com/64145819/100496277-b6582a80-3178-11eb-8c45-6c73ae23ef18.png)
![Output_2](https://user-images.githubusercontent.com/64145819/100496296-d2f46280-3178-11eb-9483-009770972f44.png)
![Output_3](https://user-images.githubusercontent.com/64145819/100496302-ebfd1380-3178-11eb-8f8c-3411fbf1bbe1.png)
![Output_4](https://user-images.githubusercontent.com/64145819/100496303-edc6d700-3178-11eb-98a5-72a830871a3e.png)
![Output_5](https://user-images.githubusercontent.com/64145819/100496311-0636f180-3179-11eb-96e5-a942dacf560d.png)
![Output_6](https://user-images.githubusercontent.com/64145819/100496316-0df69600-3179-11eb-80f8-a9326ba29c06.png)
![Output_7](https://user-images.githubusercontent.com/64145819/100496317-13ec7700-3179-11eb-86c5-099de00004c4.png)
![Output_8](https://user-images.githubusercontent.com/64145819/100496320-18189480-3179-11eb-8159-85616fe355c6.png)
![Output_9](https://user-images.githubusercontent.com/64145819/100496325-21a1fc80-3179-11eb-93f7-a4eb06a3f1ed.png)
![Output_10](https://user-images.githubusercontent.com/64145819/100496328-2666b080-3179-11eb-8151-6e3dffaa73e1.png)

**Comment by BARANI2001** [comment]
Finished issue #192 and Raised PR in learn repo @AkbarHabeeb anna. Output screenshots are attached in the comment anna

**Comment by AkbarHabeeb** [comment]
@BARANI2001 
Kindly use the reactstrap to beautify the tables. And append the changes to the same PR

**Comment by BARANI2001** [comment]
![Screenshot (475)](https://user-images.githubusercontent.com/64145819/102684005-f69c4d00-41fa-11eb-8091-ca42ff661ce2.png)
Check this @AkbarHabeeb anna

**Comment by AkbarHabeeb** [comment]
Looks good @BARANI2001
