### ISSUE TITLE
Ruby Programming Task 1

### ISSUE THREAD

**Issue by InbasasiS** [Team-Tomato/Learn#269]
Fetch news articles from NewsAPI
Implement the task in RUBY language

Steps: 
1.Create an account and get the api key in https://newsapi.org
2. Follow the documentation to get the articles: https://newsapi.org/docs/endpoints/top-headlines

Process the response:
Extract the title, description, url, source name from each article in api response.

**Comment by AkbarHabeeb** [comment]
Deferred
